### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by dwcaraway** [GSA/auctions_api#16]
The default response size (>>10MB) is very large. Suggest adding the ability to get a subset of data (e.g. pagination) with a default response size of somewhere between 50 and 200 items in the response

Possible ways to implement:
- `page` query parameter with an optional `page_size` that determines the number of responses per page
- `start` and `limit` parameter that allow arbitrary subsets of the resources of a collection (e.g. slices). similar to pages except without starting at fixed indices

for collections, also nice to put a property indicating total items in the collection and /or max number of pages.

**Comment by gbinal** [comment]
This is a good idea and is worth doing but I'd suggest closing it for now.
