### ISSUE TITLE
Console does not show up

### ISSUE THREAD

**Issue by alishalisha** [GSA/auctions_api#17]
I wanted to play around with the Console, but it does not seem to be showing up--I see a blank spot where the console should be. I'm using the latest version of Chrome, and also checked Safari.

Screenshot:
![screenshot 2014-10-01 06 04 19](https://cloud.githubusercontent.com/assets/3958678/4473399/5c1b89e6-4952-11e4-9751-fec234eb1075.png)

**Comment by kishoregh** [comment]
We have just one API call and explained it in API basics, so deleted the side nav bar 'API calls'. Thanks.
