### ISSUE TITLE
add to gsa.gov/developer

### ISSUE THREAD

**Issue by gbinal** [GSA/auctions_api#2]
@kishoregh - I think you should be able to get your API listed on gsa.gov/developer by following up on the GSA api listserve with a request.

**Comment by kishoregh** [comment]
Sent a request, will be listed soon.

**Comment by gbinal** [comment]
Suggest leaving the issue open until the gsa.gov team follows through, just to keep track.

**Comment by gbinal** [comment]
This is done.
