### ISSUE TITLE
styling off for /console

### ISSUE THREAD

**Issue by gbinal** [GSA/auctions_api#9]
I'm not sure what's up but the styling is different in a couple ways on the [API Calls page](http://gsa.github.io/auctions_api/console/).  

The main one is how the sidebar works.  Here's how I see it in Chrome on most pages:  

![screen shot 2014-09-29 at 4 13 03 pm](https://cloud.githubusercontent.com/assets/633088/4448607/0be5bd22-4815-11e4-94da-ac76cccaa656.png)  

But here's how it looks on /console:  

![screen shot 2014-09-29 at 4 12 47 pm](https://cloud.githubusercontent.com/assets/633088/4448603/ff63276a-4814-11e4-9ed4-f8c4dae3105f.png)  

I'm guessing that a link [in this file](https://github.com/GSA/auctions_api/blob/gh-pages/console/index.html) to a styling resource is broken but am not sure.  

@adelevie, @nvembar - any thoughts?

**Comment by kishoregh** [comment]
'API calls' side nav bar does not have good content, it has been deleted.
